# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11897bb9ac2585b5189972f0386f5f655265cbff318c9216aa930e3ad0e681bbaab51ad1ec04adf8e12c0a185e5603a429ef03b7fb37b1437e421702eb5af5ca

test:
  secret_key_base: 4d171861f7ad2f040322d3adafbdcc6c2ab022befeca1d5537d257944fc5fe229652a303298e58d388079f62a145190cbd767700728ab4f7b32ec62446f76c4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
